/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 6-nov-2010, 18:56:47
 */

package ww10gui;

/**
 *
 * @author guy
 */
public class WW10GUI extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public WW10GUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        tabs = new javax.swing.JTabbedPane();
        averageProfitTab = new javax.swing.JPanel();
        actionTab = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        javax.swing.GroupLayout averageProfitTabLayout = new javax.swing.GroupLayout(averageProfitTab);
        averageProfitTab.setLayout(averageProfitTabLayout);
        averageProfitTabLayout.setHorizontalGroup(
            averageProfitTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        averageProfitTabLayout.setVerticalGroup(
            averageProfitTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );

        tabs.addTab("Average Profit", averageProfitTab);

        javax.swing.GroupLayout actionTabLayout = new javax.swing.GroupLayout(actionTab);
        actionTab.setLayout(actionTabLayout);
        actionTabLayout.setHorizontalGroup(
            actionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        actionTabLayout.setVerticalGroup(
            actionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );

        tabs.addTab("Actions", actionTab);

        jSplitPane2.setBottomComponent(tabs);
        jSplitPane2.setLeftComponent(jProgressBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WW10GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionTab;
    private javax.swing.JPanel averageProfitTab;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables

}
